Citizen.CreateThread(function()
	--   porsche918spyder
	AddTextEntry('2F3202EC', '918 Spyder')
	AddTextEntry('3E4C94EC', 'installed on the original color roof')
	AddTextEntry('5A30992A', 'Weissach lightweight kit')
	AddTextEntry('9B056CA4', 'Racing type carbon fiber tail')
	AddTextEntry('162EABA2', 'Super lightweight component')
	AddTextEntry('1940E91D', 'Fixed raised carbon fiber tail')
	AddTextEntry('4385064E', 'leather luxury components')
	AddTextEntry('95488508', 'Open the engine hatch cover')
	AddTextEntry('BF9A35CD', 'Fixed rising primary color tail')
	AddTextEntry('BF49FF01', 'Porsche')
	AddTextEntry('CF34B068', 'Racing front brackets')
	AddTextEntry('D377AC71', 'Install the lightweight roof')
  end)
