Citizen.CreateThread(function()
	--   aventador
	AddTextEntry('09648119', 'LB_WORKS wide body modification kit')
	AddTextEntry('0A117B46', 'Lamborghini')
	AddTextEntry('1BCB25E6', 'ER track edition interior')
	AddTextEntry('1E1DAA83', 'DMC_LP988 body modification kit')
	AddTextEntry('2B0F8426', 'DMC carbon fiber side skirt')
	AddTextEntry('4C8825CE', 'LB_WORKS wide body large spoiler')
	AddTextEntry('6A360ABC', 'FH3 Customized carbon fiber front lip')
	AddTextEntry('6F6F764D', 'LB_WORKS Burning Blue Short Range Exhaust')
	AddTextEntry('8C50AFEF', 'SV Black Extrusion Exhaust')
	AddTextEntry('45D87A00', '50th anniversary edition of the interior modification kit')
	AddTextEntry('62DA5D23', 'Up four out of the exhaust')
	AddTextEntry('99C83004', 'ER track version after the collision')
	AddTextEntry('395B20BD', 'ER track version skirt')
	AddTextEntry('581A1E83', 'SV interior decoration kit')
	AddTextEntry('2639D92E', 'Small adjustable fixed spoiler')
	AddTextEntry('3899F8E1', 'Aventador LP700-4 Roadster')
	AddTextEntry('7129EF11', 'SV kit medium type spoiler')
	AddTextEntry('12275B44', 'SV body modification kit and engine')
	AddTextEntry('9590521F', 'Triangle vent type front cover')
	AddTextEntry('23803217', 'Exaggerated modeling back cover')
	AddTextEntry('A9A74FC2', 'DMC carbon fiber exhaust armor')
	AddTextEntry('B8AFFE1C', 'DMC carbon fiber small spoiler')
	AddTextEntry('D091D772', 'DMC carbon fiber small front lip')
	AddTextEntry('EC398EB5', 'ER track version before the collision')
	AddTextEntry('F6226A08', 'Install the roof')
	AddTextEntry('FAF96D56', '50th anniversary version of the body modification kit')
  end)
